### PR TITLE
fix example bug on result

### PR DESCRIPTION
**Pull request by zhenggc1**

### CODE REVIEW

**Comment by alfiopuglisi** [comment]
Hello zhenggc1,
thanks for the contribution, but what you are fixing is a feature, not a bug :)
`'result`' is a non-editable label
`'__result__'`  is an edit box
the example is showing the result into a label that the user cannot edit. This is on purpose, only the numbers to be added can be edited.

Or did I misunderstand your patch ?

**Comment by zhenggc1** [comment]
When i using 'result', i can't see the result value but just a word 'result' showing. I using stable version 0.3.3 on my mac pro.
And i can't see any exception, i do not why.

**Comment by zhenggc1** [comment]
Please ignore my patch, sorry for my mistake on testing the example. When i copy the code and put in python console, it's can't show the result, but when i using a file to start it, it's succeed.

**Comment by alfiopuglisi** [comment]
Ok good. Yes the 'with' syntax has problems working on the python prompt. Can I ask you which python version and MacOS version you have? are you using standard python or IPython?

**Comment by nimeshkverma** [comment]
Got the same issue. Change the variable name from `result` to `__result__`
Python Version: 3.6.7
MAC OS 10.15.1 (19B88)

**Comment by alfiopuglisi** [comment]
Thanks nimeshkverma for the report. Looks like it happens on Macs. I will try to replicate it.

**Pull request closed without merging**
